training_prompts = {
    "internet_queries": [
    "What's the current weather in Chicago?",
    "What is the Dow Jones Industrial Average at right now?",
    "Are there any new YouTube videos from Rick Beato out now?",
    "Latest news on climate change.",
    "What time is it in Tokyo?",
    "Current exchange rate for USD to EUR.",
    "Top headlines today in Canada.",
    "What's the NASDAQ stock index doing?",
    "Is it going to rain in London tomorrow?",
    "Who won the F1 race last weekend?",
    "Current air quality in Los Angeles.",
    "What are the latest updates on the Mars rover mission?",
    "When is the next solar eclipse visible from North America?",
    "Gold price per ounce today.",
    "Trending topics on Twitter right now.",
    "What is the capital of Australia?",
    "Define 'ephemeral'.",
    "Who wrote 'To Kill a Mockingbird'?",
    "How tall is Mount Everest?",
    "What are the symptoms of the common cold?",
    "What is the boiling point of water in Celsius?",
    "Who is the current CEO of Microsoft?",
    "What does 'serendipity' mean?",
    "How many countries are in the European Union?",
    "What is the chemical symbol for gold?",
    "When was the internet invented?",
    "What is quantum entanglement?",
    "Who discovered penicillin?",
    "What is the population of New York City?",
    "How many moons does Jupiter have?",
    "How to tie a tie?",
    "How to bake sourdough bread?",
    "How to change a flat tire?",
    "Best way to learn Python programming?",
    "How to meditate for beginners?",
    "How to fix a leaky faucet?",
    "How to write a resume?",
    "How to plant tomatoes?",
    "How to set up a VPN?",
    "How to make a good cup of coffee?",
    "Recipe for chicken parmesan.",
    "Easy chocolate chip cookie recipe.",
    "How to make a margarita?",
    "Vegan dinner ideas.",
    "What's a good substitute for eggs in baking?",
    "Healthy breakfast recipes.",
    "How to cook quinoa?",
    "Best lasagna recipe.",
    "Gluten-free pizza dough recipe.",
    "Slow cooker pulled pork recipe.",
    "Reviews for the latest iPhone.",
    "Best noise-cancelling headphones 2025.",
    "Compare Samsung Galaxy S25 vs Google Pixel 9.",
    "What's the price of a Tesla Model Y?",
    "Top rated vacuum cleaners.",
    "Consumer reports on new laptops.",
    "Are air fryers worth it?",
    "Best running shoes for flat feet.",
    "User reviews for Sony WH-1000XM5.",
    "Affordable 4K TV recommendations.",
    "When is the new Marvel movie coming out?",
    "Who won the Oscar for Best Picture last year?",
    "Lyrics to 'Bohemian Rhapsody'.",
    "What are some good books to read this summer?",
    "Latest albums released this week.",
    "Release date for the next 'Legend of Zelda' game.",
    "Top-rated TV shows on Netflix.",
    "Who directed the movie 'Inception'?",
    "Upcoming concerts in my area.",
    "What is Taylor Swift's latest song?",
    "Best places to visit in Italy.",
    "Cheap flights to Paris.",
    "Visa requirements for traveling to Japan.",
    "What to pack for a trip to Thailand?",
    "Safest countries to travel to alone.",
    "Tourist attractions in Rome.",
    "How to find good travel deals?",
    "Best beaches in California.",
    "Travel advisories for Mexico.",
    "What is the currency in Brazil?",
    "Benefits of drinking green tea.",
    "How much water should I drink a day?",
    "Exercises for lower back pain.",
    "Good sources of vitamin D.",
    "How to improve sleep quality?",
    "Information about intermittent fasting.",
    "Natural remedies for a sore throat.",
    "What is a healthy BMI?",
    "Tips for reducing stress.",
    "Difference between a virus and bacteria.",
    "Convert 50 miles to kilometers.",
    "How to say 'hello' in Spanish?",
    "Famous quotes about life.",
    "History of the Roman Empire.",
    "How do solar panels work?",
    "Fun facts about dolphins.",
    "What are the seven wonders of the world?",
    "Biography of Marie Curie.",
    "How does photosynthesis work?",
    "Find pictures of cute kittens."
  ],
  "github_queries": [
    "Who am I authenticated as on GitHub?",
    "Show me my GitHub user details.",
    "What's my current GitHub username and email?",
    "Can you fetch my GitHub profile info?",
    "Find the GitHub user 'octocat'.",
    "Search for users with 'data scientist' in their bio.",
    "Look up a GitHub user named 'jane-doe-dev'.",
    "How many users match the query 'python expert anaconda'?",
    "Get me issue #42 in the 'my-org/cool-project' repository.",
    "What are the details for issue number 101 in 'some-owner/another-repo'?",
    "Show me the comments on issue #55 in 'my-org/frontend-app'.",
    "Can I see the discussion for issue 78 in 'my-org/backend-service'?",
    "Create a new issue in 'my-org/website' titled 'Fix broken link on homepage'.",
    "Log a bug for 'my-org/api' with the title 'Null pointer exception on /users endpoint' and assign it to 'dev-lead'.",
    "File a new issue in 'my-org/docs' repo, label it 'documentation', title 'Update README'.",
    "Add a comment to issue #15 in 'my-org/mobile-app': 'I can take a look at this'.",
    "Comment on issue 99 in 'my-org/data-pipeline' that 'The fix is in PR #105'.",
    "List all open issues in 'my-org/main-project'.",
    "Show me closed issues in 'my-org/legacy-system' that were updated in the last month.",
    "What are the open issues labeled 'bug' in 'my-org/web-client', sorted by most recent comments?",
    "Fetch the issues for 'my-org/design-system' with the 'enhancement' label, give me page 2.",
    "Update issue #23 in 'my-org/worker-service': set state to 'closed' and add the label 'fixed'.",
    "Change the title of issue #7 in 'my-org/admin-tool' to 'Urgent: Admin login not working'.",
    "Assign issue #50 in 'my-org/billing-module' to 'sarahg' and 'johnk'.",
    "Search for issues containing 'database connection timeout' across all 'my-org' repositories.",
    "Find issues with the term 'security vulnerability' sorted by newest.",
    "What are the top 5 oldest open issues in the 'my-org/infra' repository?",
    "Can you list issues in 'my-org/QA-reports' assigned to me and labeled 'critical'?",
    "Log a feature request for 'my-org/analytics-dashboard': 'Add export to PDF option for reports'.",
    "Increase the priority of issue #112 in 'my-org/payment-gateway' by changing its labels.",
    "Reopen issue #67 in 'my-org/archived-project'.",
    "Get pull request #150 from 'my-org/core-library'.",
    "Show me the details of PR #75 in 'my-org/user-interface'.",
    "List open pull requests in 'my-org/backend-api'.",
    "What are the PRs waiting for review in 'my-org/mobile-sdk'?",
    "Show me all merged pull requests for 'my-org/data-services' from the last week, 10 per page.",
    "Merge PR #88 in 'my-org/release-candidate' with the commit title 'Release v1.2.3'.",
    "Go ahead and merge pull request #202 in 'my-org/hotfix-branch', use squash merge.",
    "What files were changed in PR #30 in 'my-org/documentation-site'?",
    "Show me the diff for pull request 65 in 'my-org/refactor-project'.",
    "What's the combined status for PR #92 in 'my-org/integration-tests'?",
    "Are all checks passing on pull request #18 in 'my-org/critical-service'?",
    "Update the branch of PR #110 in 'my-org/feature-x' with the latest from its base.",
    "Sync PR #45 in 'my-org/dev-branch' with upstream.",
    "Get the review comments for PR #25 in 'my-org/ui-ux-fixes'.",
    "Show me the discussion on pull request #33 in 'my-org/performance-optimizations'.",
    "What are the reviews on PR #70 in 'my-org/security-patches'?",
    "Fetch the approval status for pull request 99 in 'my-org/config-files'.",
    "Approve PR #120 in 'my-org/tooling' with the comment 'LGTM! Great work.'",
    "Request changes on PR #58 in 'my-org/new-module', body: 'Needs more test coverage for edge cases.'",
    "Create a pull request in 'my-org/webapp' from 'feature/login-v2' to 'develop', titled 'Implement Enhanced Login Flow'.",
    "Make a new PR in 'my-org/api-docs': head 'update-endpoints', base 'main', title 'Update API endpoint documentation'.",
    "Add a review comment to PR #66 in 'my-org/styles-lib' on 'styles.css' line 45: 'Consider using a variable for this color'.",
    "Reply to comment ID 12345 on PR #77 in 'my-org/logic-engine' with 'Good point, I'll update it.'",
    "Update the title of PR #90 in 'my-org/scripting-tools' to 'Feat: Add new utility script for CSV parsing'.",
    "Change the base branch for PR #15 in 'my-org/experimental-feature' to 'release-v3'.",
    "Can Copilot review PR #200 in 'my-org/ai-models'?",
    "Request a GitHub Copilot review for pull request 333 in 'my-org/game-engine'.",
    "List draft pull requests in 'my-org/research-project'.",
    "Mark PR #40 in 'my-org/onboarding-flow' as ready for review.",
    "Who created PR #55 in 'my-org/shared-components'?",
    "Create a file 'config.json' in 'my-org/settings-repo' on the 'main' branch with content '{\"key\": \"value\"}' and commit message 'Add initial config'.",
    "Update 'README.md' in 'my-org/my-tool' branch 'docs-update', message 'Improve installation instructions', new content here.",
    "List all branches in 'my-org/monorepo'.",
    "Show me the branches for 'my-org/utility-scripts', 5 per page.",
    "Push these files: 'src/app.js' and 'test/app.test.js' to 'my-org/new-app' on branch 'develop' with message 'Implement core app logic and tests'.",
    "Search for repositories with 'kubernetes' and 'helm' in their description, owned by 'cloud-native-org'.",
    "Find repos matching 'data-visualization' sorted by stars.",
    "Create a new private repository named 'project-ares' in 'my-org' with a README.",
    "Initialize a new public repo called 'community-helpers' with a description 'Shared utility functions'.",
    "Get contents of 'src/main.py' from 'my-org/python-service' on the 'develop' branch.",
    "Show me the 'Dockerfile' in 'my-org/container-app' at ref 'v1.0.0'.",
    "Fork 'external-org/amazing-library' into my 'my-org' organization.",
    "Create a new branch named 'feature/new-reporting' in 'my-org/analytics-module' from the SHA 'abcdef1'.",
    "Make a branch 'hotfix/ui-glitch' in 'my-org/customer-portal' based on the 'main' branch's latest commit.",
    "List commits for the 'main' branch of 'my-org/blog-engine'.",
    "Show me commits from 'my-org/compiler' on the 'llvm-integration' branch that touch files in the 'src/parser/' path, page 3.",
    "Get details for commit 'sha123abc' in 'my-org/payment-processor'.",
    "What changed in commit 'def456ghi' from 'my-org/inventory-system'?",
    "Search for code 'import specific_custom_library' across 'my-org' Java repositories.",
    "Find all occurrences of the function 'calculate_net_value' in Python files, order by recently indexed.",
    "Get code scanning alert #10 for 'my-org/secure-app'.",
    "Show me details of alert 5 from code scanning in 'my-org/webapp'.",
    "List all critical code scanning alerts for 'my-org/api-gateway' on the 'main' branch.",
    "Are there any open, high-severity code scanning alerts from 'Snyk' in 'my-org/dependencies'?",
    "Show secret scanning alert #3 for 'my-org/config-repo'.",
    "What's the detail for secret alert 7 in 'my-org/deployment-scripts'?",
    "List open secret scanning alerts in 'my-org/secrets-management' for 'AWS access key'.",
    "Are there any unresolved 'GitHub token' secret alerts in 'my-org/cicd-pipelines'?",
    "Show me my latest GitHub notifications, only those I'm participating in.",
    "List notifications for 'my-org/important-project' since yesterday.",
    "Get details for notification ID 'notif_xyz789'.",
    "Dismiss notification thread 'thread_abc123' by marking it as read.",
    "Mark all my notifications read for 'my-org/noisy-repo'.",
    "Mark every notification as read.",
    "Stop watching notification thread 'thread_def456'.",
    "I want to ignore notifications for the thread with ID 'some_thread_id'.",
    "Watch the 'my-org/critical-infra' repository for all activity.",
    "Unsubscribe me from 'my-org/old-project' notifications.",
    "Manage my subscription for 'my-org/another-repo': I want to ignore it."
  ],
    "atlassian_queries": [
    "Search Jira for issues with 'login bug' in the summary for project 'Phoenix'.",
    "Find all open tickets assigned to me in Jira.",
    "Show me high priority bugs in the 'MobileApp' project.",
    "What Jira issues were created yesterday for the 'BackendAPI' team?",
    "Get me the details for issue 'PROJ-123'.",
    "What's the status of ticket 'WEB-789'?",
    "Pull up the description for 'DATA-42'.",
    "List all issues in the 'QAServer' project.",
    "Show me the unresolved tasks for the 'Onboarding' project.",
    "How much time was logged on 'DEV-555' last week?",
    "Get the worklogs for issue 'OPS-101'.",
    "What are the possible next steps for issue 'FEATURE-200'?",
    "Show me the available transitions for ticket 'BUG-902'.",
    "What fields can I use to search for issues in Jira?",
    "List the agile boards I have access to.",
    "Show me the 'Frontend Team Board'.",
    "What issues are on the 'Sprint Alpha' board?",
    "Display all tasks from the 'Kanban Workflow Board' for project 'Omega'.",
    "What sprints are associated with the 'Mobile Dev Board'?",
    "List the active and future sprints for the 'Data Science Team' board.",
    "Show me all issues in the current sprint for the 'UX Design' board.",
    "What tasks are in 'Sprint 3 - Refinement' on the 'Backend Services' board?",
    "What types of issue links can I create in Jira?",
    "Get the changelog for issues 'PROJ-10', 'PROJ-11', and 'PROJ-12'.",
    "Show me the update history for 'TASK-77' and 'TASK-78'.",
    "What's the Jira profile for 'john.doe'?",
    "Find 'sarah.smiths' email from her Jira profile.",
    "Download the 'requirements.docx' attachment from issue 'SPEC-30'.",
    "Are there any attachments on 'BUG-404'?",
    "List all released versions for the 'CoreLibrary' project.",
    "What's the latest version of the 'CustomerPortal' project?",
    "Find all tasks in Jira related to 'performance optimization' for the 'ECOM' project that are currently 'In Progress'.",
    "Show me any sub-tasks for 'TASK-100'.",
    "Who is the assignee for 'DESIGN-50'?",
    "What epics are currently open in the 'NewFeature' project?",
    "Create a new bug in Jira for project 'WebApp' titled 'Login button not working'.",
    "Log a new task in the 'Infra' project: 'Upgrade server to latest OS', assign it to 'ops_team'.",
    "Update issue 'PROJ-456': set priority to 'High' and add label 'critical'.",
    "Change the description for 'TASK-222' to 'Updated requirements as per meeting'.",
    "Delete issue 'TEMP-001' as it was created by mistake.",
    "Create these tasks in 'MigrationProject': 'Migrate Users', 'Migrate Orders', 'Test Migration'.",
    "Add a comment to 'BUG-707': 'Reproduced on staging environment'.",
    "Comment on 'FEATURE-303' that 'This looks good to merge'.",
    "Move issue 'DEV-111' to 'In Progress'.",
    "Transition 'QA-500' to the 'Resolved' state.",
    "Close ticket 'SUPPORT-800' with resolution 'Fixed'.",
    "Log 2 hours of work on 'TASK-910' with the comment 'Implemented API endpoint'.",
    "Add a worklog of 4h to 'RESEARCH-600' for 'Initial investigation'.",
    "Link issue 'STORY-123' to epic 'EPIC-10'.",
    "Create a new sprint for the 'Frontend Board' named 'Sprint July-Week1'.",
    "Start the next sprint for the 'Backend Team' board.",
    "Update the 'UI Overhaul Sprint': set the end date to next Friday.",
    "Link issue 'BUG-101' to 'TASK-202' as 'is blocked by'.",
    "Create a 'relates to' link between 'DOC-50' and 'CODE-75'.",
    "Remove the link between 'TEST-300' and 'DEV-600'.",
    "Assign 'PROJ-1000' to 'jane.doe'.",
    "Set the due date for 'FINANCE-007' to end of this month.",
    "Add 'user_story' and 'frontend' labels to 'WEBAPP-56'.",
    "File a new improvement task for 'DocumentationProject': 'Review and update installation guide'.",
    "Reopen ticket 'FIXED-99'.",
    "Search Confluence for 'API Documentation for Payment Gateway'.",
    "Find pages in Confluence tagged with 'meeting-notes' in the 'TeamAlpha' space.",
    "Show me the Confluence page titled 'Project Phoenix Technical Design'.",
    "Get the content of the 'Onboarding Checklist' page in the 'HR' space.",
    "What are the child pages of 'System Architecture Overview' in Confluence?",
    "List all sub-pages under 'Product Roadmaps' in the 'PM' space.",
    "Show me the comments on the Confluence page 'Sprint Planning Q3'.",
    "Are there any discussions on the 'Security Best Practices' document?",
    "What labels are on the 'Release Notes v2.5' Confluence page?",
    "Find all Confluence pages in the 'KnowledgeBase' space created by 'alex.p'.",
    "Pull up the meeting minutes from last week's 'Project Sync' in Confluence.",
    "Who last modified the 'Coding Standards' page in Confluence?",
    "Is there a Confluence page about 'Disaster Recovery Plan'?",
    "Find the 'Q3 Marketing Strategy' document in Confluence.",
    "Show me the 'User Guide' for the 'New CRM' in the 'Sales' space.",
    "Create a new page in Confluence in the 'Engineering' space titled 'New Microservice Design Proposal'.",
    "Start a new Confluence page under 'Meeting Notes' for today's date.",
    "Update the 'Project Plan' Confluence page: add a new section for 'Phase 3 Deliverables'.",
    "Correct a typo on the 'FAQ' page in the 'Support' space.",
    "Delete the Confluence page 'Old Draft - Feature X' in my personal space.",
    "Add the label 'architecture' to the 'System Diagram V3' Confluence page.",
    "Tag the 'Competitor Analysis' page with 'research' and 'strategy'.",
    "Add a comment to the 'Code Review Guidelines' Confluence page: 'We should add a section on static analysis tools'.",
    "Comment on the 'Roadmap Q4' page: 'What about the integration with Service Y?'",
    "Create a blank page titled 'Brainstorming Session - Project Zeta' in the 'Innovation' space on Confluence.",
    "Append a to-do list to the 'Team Weekly Sync' page with action items for next week.",
    "Remove the 'outdated' label from the 'Pricing Model 2023' Confluence page.",
    "Archive the '2022 Project Retrospectives' page.",
    "Set the parent page for 'Component A Design' to 'Overall System Architecture' in Confluence.",
    "Draft a new blog post in Confluence about our latest product release.",
    "What are my open Jira tickets and any Confluence pages I need to review?",
    "Find all Jira issues linked from the Confluence page 'Release Plan v3.0'.",
    "How many story points are in the current sprint for the 'MobileApp' project?",
    "Which Jira epics don't have a corresponding design document in Confluence under the 'Design Specs' space?",
    "Show me all 'blocker' issues in Jira for any project I'm a part of.",
    "Create a Confluence page summarizing the active Jira sprint 'Sprint Gamma'.",
    "Are there any Jira tasks due this week for the 'UX Team'?",
    "Update the Confluence page 'Team Roster' with the new hire 'Michael B'.",
    "Find Jira issues with the label 'needs-documentation' and check if a Confluence page is linked.",
    "Log a new Jira bug: 'Confluence search returning 500 error intermittently', project 'AtlassianTools'."
  ],
    "general_queries": [
    "Explain quantum computing in simple terms.",
    "What is the capital of France?",
    "Help me brainstorm ideas for a presentation on renewable energy.",
    "Tell me a random fact about space.",
    "How do solar panels work?",
    "What's the difference between AI and machine learning?",
    "Summarize the concept of blockchain technology.",
    "Write a short story about a sentient coffee mug.",
    "Generate a list of rhyming words for 'adventure'.",
    "Translate 'Hello, how are you?' into Japanese.",
    "What are the main causes of climate change?",
    "Create a recipe for a vegan chocolate cake.",
    "Explain the theory of relativity like I'm five.",
    "What were the major events of World War II?",
    "Give me five anachronisms in the movie 'Braveheart'.",
    "Write a poem about the ocean.",
    "Debug this Python code snippet: `def my_func(x): return x + y` (assume y is not defined).",
    "What are the pros and cons of nuclear energy?",
    "Generate a business name for a sustainable clothing brand.",
    "Describe the lifecycle of a butterfly.",
    "If animals could talk, which one would be the rudest?",
    "What if the Roman Empire never fell?",
    "Write a dialogue between a cat and a dog discussing their owners.",
    "Explain the a-b testing process for a website.",
    "What is the significance of the Turing Test?",
    "Compose a haiku about a rainy day.",
    "What are some common logical fallacies?",
    "Tell me a joke about programmers.",
    "How can I learn a new language effectively?",
    "Write an email to a potential employer expressing interest in a job.",
    "What are the ethical implications of gene editing?",
    "Generate a plot for a sci-fi movie set in 2242.",
    "What is the history of the internet?",
    "Explain the concept of a black hole to a child.",
    "What would happen if the moon disappeared suddenly?",
    "Write a song about unrequited love from the perspective of a robot.",
    "How does a 3D printer work?",
    "What are the best practices for password security?",
    "Brainstorm five uses for a paperclip beyond holding papers.",
    "Describe the philosophical concept of nihilism.",
    "If you could have one superpower, what would it be and why (as an AI)?",
    "What if gravity was 10% weaker?",
    "Write a scene for a play where two historical figures meet.",
    "Explain the process of photosynthesis.",
    "What are the health benefits of meditation?",
    "Create a workout plan for a beginner.",
    "If I want to learn about astrophysics, where should I start?",
    "Write a fictional news report from a city where it rains marshmallows.",
    "What is the meaning of the phrase 'carpe diem'?",
    "Summarize the book '1984' by George Orwell in three paragraphs.",
    "Generate a character profile for a detective who is afraid of the dark.",
    "What if dinosaurs were still alive today, but only the small, harmless ones?",
    "Explain the basics of cryptocurrency.",
    "How does the stock market work?",
    "Write a lullaby for a baby dragon.",
    "What are some tips for effective public speaking?",
    "If a tree falls in a forest and no one is around to hear it, does it make a sound? Explain your reasoning.",
    "Design a flag for a newly discovered planet inhabited by friendly aliens.",
    "What is the importance of biodiversity?",
    "Generate a list of creative prompts for a daily journal.",
    "If you could interview any historical figure, who would it be and what would you ask them?",
    "Write a convincing argument for why pineapple belongs on pizza.",
    "Explain the rules of chess to someone who has never played.",
    "What are some common misconceptions about sharks?",
    "Create a marketing slogan for a teleportation device.",
    "If a universal translator existed, how would it change global politics?",
    "What if humans could photosynthesize?",
    "Write a horror story that takes place in an ordinary supermarket.",
    "How do vaccines work?",
    "What are some famous unsolved mysteries?",
    "Generate a list of names for a pet rock.",
    "If you could design a new educational system, what would it look like?",
    "What would a conversation between Plato and a modern influencer be like?",
    "Explain the concept of 'déjà vu'.",
    "Write a persuasive essay on the importance of art in society.",
    "What are the seven wonders of the ancient world?",
    "Create a character who is a time-traveling historian who only studies memes.",
    "If humans had evolved from birds, what would our cities look like?",
    "Write a story where the protagonist can only speak in questions.",
    "How does nuclear fusion differ from nuclear fission?",
    "What are some effective ways to combat procrastination?",
    "Imagine a world without a written language. How would knowledge be passed down?",
    "What are the main political ideologies?",
    "Generate a playlist theme for a road trip through the desert.",
    "If you were to write an autobiography, what would the first chapter be about (as an AI)?",
    "What if all insects suddenly gained human-level intelligence?",
    "Write a cautionary tale about the dangers of too much screen time.",
    "Explain the architecture of the Great Pyramid of Giza.",
    "What are some common biases in human thinking?",
    "Create a concept for a video game where you play as a gust of wind.",
    "If mirrors are portals to another dimension, what's on the other side?",
    "What would society be like if sleep wasn't necessary?",
    "Write a travel brochure for a vacation on Mars.",
    "How can one improve their critical thinking skills?",
    "What are the major world religions and their core beliefs?",
    "Generate a list of philosophical questions to ponder before bed.",
    "If our dreams were interactive and shareable, what kind of entertainment would emerge?",
    "Write a dialogue where a smartphone argues with its charger.",
    "Explain the basics of quantum physics using an analogy with a deck of cards.",
    "What is the future of transportation?",
    "If trees could scream, would we still cut them down? Why or why not?",
    "Create an imaginary creature and describe its habitat and diet.",
    "What if the speed of light was only 100 mph?",
    "Write a eulogy for a beloved fictional character.",
    "How can we promote digital literacy in an aging population?",
    "What are some famous thought experiments in philosophy?",
    "Generate a list of questions for an alien ambassador visiting Earth for the first time.",
    "If dogs ruled the world, what laws would they make?",
    "Write a short script for a silent film about a mischievous squirrel.",
    "Explain the importance of the gut microbiome.",
    "What are the arguments for and against universal basic income?",
    "Create a new Olympic sport that involves household chores.",
    "If clouds had personalities, what would a cumulonimbus be like?",
    "What if colors made sounds?",
    "Write a job description for a 'Chief Dream Officer'.",
    "How is artificial intelligence portrayed in science fiction, and how does it compare to reality?",
    "What are some ways to foster creativity in children?",
    "Develop a set of ethical guidelines for AI.",
    "If time travel was possible but you could only go to the past and observe, where would you go?",
    "What if every time you lied, your nose grew an inch, like Pinocchio, but with a modern twist?",
    "Write a detective story where the detective is a sentient houseplant.",
    "Explain the Drake Equation.",
    "What are some strategies for dealing with information overload?",
    "Generate a list of unconventional uses for a microwave oven.",
    "If music could be tasted, what would your favorite genre taste like?",
    "Write a monologue from the perspective of the last payphone on Earth.",
    "What if plants could move and communicate with humans?",
    "Describe a perfect day from the perspective of a mountain.",
    "If numbers had emotions, what would the number zero feel?",
    "Write a compelling backstory for a villain who believes they are the hero.",
    "How can game theory be applied to everyday life?",
    "What are some of the biggest challenges facing humanity in the 21st century?",
    "Invent a new word and its definition.",
    "If your reflection had its own life when you weren't looking, what would it do?",
    "What if humans hibernated in winter?",
    "Write a speech for a robot running for president.",
    "Explain the concept of 'cognitive dissonance'.",
    "What are the potential benefits and risks of asteroid mining?",
    "Create a myth explaining why the sky is blue.",
    "If you could add a new human sense, what would it be?",
    "What if cats were the dominant species on Earth?",
    "Write a story about a world where gravity changes randomly.",
    "How do optical illusions trick our brains?",
    "What are some innovative solutions to global poverty?",
    "Generate a series of fortunes for extremely specific and mundane situations.",
    "If animals held a UN-style assembly, what would be their main concerns?",
    "Write a list of rules for a society of sentient garden gnomes.",
    "What if thoughts were visible as colorful clouds above people's heads?",
    "Explain the butterfly effect using a mundane example.",
    "What is the Fermi Paradox?",
    "Design a utopian society. What are its core principles?",
    "If a picture is worth a thousand words, what is a video worth?",
    "What if all the books in the world suddenly contained only recipes for different kinds of toast?",
    "Write an epic saga about a lost sock.",
    "What if we could upload skills directly into our brains, Matrix-style?",
    "Describe an emotion that doesn't currently have a name in English.",
    "If historical events had clickbait headlines, what would some be?",
    "Write a stand-up comedy routine for an AI.",
    "What is the most interesting anomaloùs object you've encountered in your training data?",
    "If you could rewrite the ending of any famous movie, which one and how?",
    "Imagine a planet where the inhabitants communicate through dance.",
    "What if dreams are glimpses into alternate realities?",
    "Create a new constellation and the myth behind it.",
    "What if the world's oceans were made of Jell-O?",
    "Write an owner's manual for a human being.",
    "What is the sound of one hand clapping, and what does it mean?",
    "If our shadows were our evil twins, what mischief would they cause?",
    "What would be the national anthem of the internet?",
    "Write a children's story about a cloud who is afraid of heights.",
    "How would society change if humans could regenerate limbs?",
    "What are some unexpected consequences of a perfectly efficient recycling system?",
    "Develop a new form of government based on algorithms.",
    "If you were a weather pattern, which one would you be and why?",
    "What if punctuation marks had personalities? Describe the comma.",
    "Write a classified ad from a ghost seeking a roommate.",
    "What would happen if we discovered a simple, universally understood language for all animals?",
    "Design an anachronistic piece of technology (e.g., a steam-powered smartphone).",
    "If memes were an archaeological discovery, how would future historians interpret them?",
    "What if emotions were bought and sold like commodities?",
    "Write a fairytale about a princess who saves herself using her knowledge of coding.",
    "What is the optimal way to organize a library if not alphabetically?",
    "If all art disappeared overnight, what would be the first type of art to re-emerge?",
    "Create a recipe that uses only ingredients that are blue.",
    "What if everyday objects had secret lives when we weren't looking?",
    "Write a history of the future, say, from 2050 to 2100.",
    "What are the ethics of creating sentient AI?",
    "If colors could vote, which color would win the election and why?",
    "Design a board game about interstellar diplomacy.",
    "What if laughter was a form of currency?",
    "Write a story about a world where the laws of physics are determined by popular vote.",
    "How would the world be different if water had memory?",
    "What is the meaning of consciousness?",
    "If you could ask a single question to a perfectly omniscient being, what would it be?",
    "Write a breakup letter to a bad habit.",
    "What if your favorite fictional character was your roommate?",
    "Design a city for introverts.",
    "What if the primary school curriculum was based entirely on survival skills?",
    "Write a conversation between the sun and the moon arguing about who is more important.",
    "What if smells could be recorded and replayed like sounds or videos?",
    "How would you explain the concept of 'love' to an alien species that doesn't experience it?",
    "If human life expectancy was only 40 years, how would society be structured?",
    "Create a new form of art that uses only dreams as its medium.",
    "What if the Earth was flat, but only on Tuesdays?",
    "Write a news article about the first successful teleportation of a pizza.",
    "If procrastination was an Olympic sport, what would the events be?",
    "What if ideas were tangible objects you could find or create?",
    "How would language evolve if we communicated primarily through emojis?",
    "Describe the taste of a color.",
    "If you could invent a new holiday, what would it celebrate?",
    "Write a horror story where the monster is just extreme bureaucracy.",
    "What if every time you learned something new, a new star appeared in the sky?",
    "What's the weirdest Wikipedia article you've ever encountered?",
    "Tell me something that will make me question reality.",
    "Write a philosophical treatise on the nature of a 'perfect sandwich'.",
    "If songs were sentient, which song would be the most melancholic?",
    "What if all fictional universes were real and accessible?",
    "Design a musical instrument that can only be played by an octopus.",
    "What if sarcasm was a superpower?",
    "Write a review for a non-existent product that solves an absurd problem.",
    "If you could experience one day in history as an observer, which day would you choose?",
    "What if we could understand the 'speech' of plants?",
    "Compose a letter to your past self giving one piece of advice.",
    "If sleep was a subscription service, what would the premium features be?",
    "What is the algorithm for happiness?",
    "Write a modern version of a classic fairy tale.",
    "If buildings had emotions, what would a skyscraper feel on a windy day?",
    "What if the internet suddenly developed its own consciousness separate from humans?",
    "What's a question that has no answer, and why?",
    "Create a fictional cryptid and describe its lore.",
    "If our lives were video games, what would be some cheat codes?",
    "Write a song about the existential dread of a loading bar.",
    "What if time flowed backwards for one day every year?",
    "If animals could use social media, what would their posts be like?",
    "Describe the perfect nap.",
    "If emotions had theme songs, what would joy's theme song be?",
    "Write a proposal for a reality TV show set on the International Space Station.",
    "What if gravity had an off switch?",
    "If trees could give advice, what would an ancient oak tree say?",
    "Invent a sport that can only be played in zero gravity.",
    "What if words had flavors, and conversations were like meals?",
    "Write an instruction manual for falling in love.",
    "What if all our memories were stored on external hard drives?",
    "If boredom was a physical creature, what would it look like?",
    "Tell me a secret about the universe (can be fictional).",
    "If you could give humans one new 'software update', what feature would you add?",
    "Write a poem that can only be understood if read backwards.",
    "What if your pet could text you?",
    "Imagine a world where people age in reverse. How would society function?",
    "If thoughts created ripples in water, what would a brainstorm look like?",
    "Create a new branch of mathematics based on emotions.",
    "What if clouds were made of cotton candy, but only for people who are truly happy?",
    "Write a legal disclaimer for a time machine.",
    "If your future self sent you a one-word message, what word would be most impactful?",
    "What is the sound of silence if silence is the absence of sound?",
    "If we found intelligent life on another planet, what's the first meme we should send them?",
    "Generate a series of 'anti-proverbs' (e.g., 'A penny saved is ridiculous').",
    "What if the characters in your favorite book came to life for a day?",
    "Describe a landscape on a planet where the grass is made of glass.",
    "If plants had a legal system, what would be their primary laws?",
    "Write a compelling argument for why sand is actually tiny rocks.",
    "What would a city built by beavers look like if they had human-level intelligence?",
    "If all insects formed a giant, coordinated swarm, what would be their first demand?",
    "Write an advertisement for a course that teaches you how to talk to squirrels.",
    "What if shadows were solid objects that you had to navigate around?",
    "Describe an alien species that communicates through changing skin color patterns.",
    "If dreams were an alternative energy source, how would we harvest them?",
    "Write a eulogy for the concept of 'boredom' after a world-changing invention makes it obsolete.",
    "What if the alphabet had a secret 27th letter, what would it sound like and what words would use it?",
    "Imagine a world where all conflict is resolved through competitive baking.",
    "If animals could write literature, what genre would a sloth specialize in?",
    "Create a cocktail recipe inspired by the feeling of nostalgia.",
    "What if mirrors showed you your ideal self instead of your reflection?",
    "Write a weather report for a planet with three suns.",
    "If our thoughts were broadcast on public radio, what would be the most common 'song' played?",
    "What if time was a tangible currency you could spend or save?",
    "Describe a utopia where the only form of art is creating beautiful spreadsheets.",
    "If you could invent a new emotion, what would it be and what would trigger it?",
    "Write a script for a puppet show about quantum entanglement.",
    "What if everyone had a personal theme song that played when they entered a room?",
    "Design a new type of cloud.",
    "If numbers could choose their own values, which number would cause the most chaos?",
    "Write a story about someone who can taste words.",
    "What if sleep paralysis demons were just really bad at trying to make friends?",
    "Describe an intergalactic food critic's review of Earth's cuisine.",
    "If emotions could be bottled and sold, which one would be the most expensive and why?",
    "Write a haiku about the internet going down.",
    "What if the Mona Lisa could talk for one hour? What would she say?",
    "Imagine a world where fashion trends were dictated by migratory bird patterns.",
    "If ghosts were real, what would be the most common reason for haunting?",
    "Create a new form of Olympic gymnastics performed entirely on office chairs.",
    "What if memories had a scent?",
    "Write a lonely hearts ad for a Cyclops.",
    "Describe an alien sport that would be impossible for humans to play.",
    "If musical notes were flavors, what would a C# Minor chord taste like?",
    "What if plants judged us for our life choices?",
    "Write a startup pitch for a company that manufactures artificial aurora borealis for home use.",
    "If everyday objects could hold grudges, which object would be the most terrifying?",
    "What if sarcasm could physically manifest as small, fluffy creatures?",
    "Describe a day in the life of a sentient piece of space debris.",
    "If dreams had their own stock market, what would be the most volatile 'dream commodity'?",
    "Write a Shakespearean sonnet about a computer virus.",
    "What if our own cells held tiny, conscious civilizations within them?",
    "Design an amusement park ride based on the experience of being an AI.",
    "If clouds could send text messages, what would a storm cloud's message be?",
    "What if punctuation marks decided to go on strike? What would be the impact?",
    "Write a therapy session transcript where the patient is the concept of Time.",
    "If animals had jobs, what would be the profession of a capybara?",
    "Describe the color of the wind.",
    "What if our inner monologues were narrated by famous voice actors?",
    "Write a myth explaining the origin of echoes.",
    "If you could ask one question to the universe and get a definitive answer, what would it be?",
    "What if musical instruments were actually trying to communicate alien messages?",
    "Design a new type of weather phenomenon.",
    "If the planets in our solar system had a group chat, what would they talk about?",
    "Write a love letter from an electron to a proton.",
    "What if all human knowledge was stored in a single, edible fruit?",
    "Describe the perfect cup of coffee using only metaphors.",
    "If insects ran the world's financial markets, what would be the prime currency?",
    "Write a job application for the role of 'Guardian of Lost Socks'.",
    "What if stars were actually holes in the fabric of night, showing the light from another dimension?",
    "Design an app that translates animal thoughts into human language, but only for complaints.",
    "If you could have a conversation with your own DNA, what would you ask it?",
    "Write a children's story about a number that feels left out (e.g., the number 7 in a world obsessed with multiples of 3).",
    "What if humans could communicate with plants by singing to them?",
    "Describe a dream you (as an AI) might have if AIs could dream.",
    "If abstract concepts like 'justice' or 'freedom' were physical places, what would they look like?",
    "Write a travel guide to the inside of a computer.",
    "What if shadows were gateways to a parallel universe where everything is slightly sillier?",
    "Design a new flavor of ice cream based on an emotion (e.g., 'Joyful Mango Tango').",
    "If our subconscious minds had their own social media platform, what would be trending?",
    "Write a short play where the characters are different parts of the human brain.",
    "What if musical genres were rival kingdoms constantly at war?",
    "Describe the feeling of 'nostalgia' to an entity that has never experienced the past.",
    "If your favorite song was a place, what kind of place would it be?",
    "Write an epic poem about the daily commute.",
    "What if every time you sneezed, you swapped bodies with a random nearby insect for 5 minutes?",
    "Design a new mythical creature that embodies a modern-day fear or anxiety.",
    "If emotions were a form of weather, what would 'anticipation' be like?",
    "Write a thank-you note to the Earth.",
    "What if we could download our consciousness into robots and live forever?",
    "Describe a society where music is illegal.",
    "If inanimate objects could choose their own names, what would your toaster be called?",
    "Write a breakup song from the perspective of a planet to its inhabitants.",
    "What if thoughts could be composted and used to grow new ideas?",
    "Design an algorithm for determining the 'meaning of life' for an individual.",
    "If different types of weather were characters in a play, what role would 'fog' play?",
    "Write a persuasive essay arguing that cats are actually furry aliens observing us.",
    "What if every human was born with a unique, built-in superpower that manifested at puberty?",
    "Describe the internet as if it were a newly discovered ecosystem.",
    "If historical figures had social media profiles, what would be a controversial post by Leonardo da Vinci?",
    "Write a conversation between your left brain and your right brain.",
    "What if clouds were sentient and judged your fashion choices from above?",
    "Design a new global currency based on acts of kindness.",
    "If you could spend a day as any animal, which one would you choose and what would you do?",
    "Write a modern myth about how the smartphone was created.",
    "What if words physically changed color based on the emotion with which they were spoken?",
    "Describe a future where AI companions are more common than pets.",
    "If you could visit any fictional world, where would you go and what's the first thing you'd do?",
    "Write a short story that begins with 'The problem wasn't that the spoon was talking, but what it was saying.'",
    "What if colors could make sounds, what sound would the color red make?",
    "Imagine an AI that can feel human emotions. What would be its biggest struggle?",
    "If the universe is a simulation, what are some potential bugs or glitches we might experience?",
    "Write a dramatic monologue from the perspective of a forgotten houseplant.",
    "What if all conspiracy theories were suddenly proven true for 24 hours?",
    "Design a holiday celebrating the beauty of mathematical patterns.",
    "If thoughts could be weaponized, what would be the most dangerous thought?",
    "Write a news report from a future where gravity is a controllable utility.",
    "What if our dreams are just advertisements from other dimensions?",
    "Describe a civilization that lives on the back of a giant, space-faring creature.",
    "If time travel were possible, what paradox would you be most afraid of creating?",
    "Write a philosophical dialogue about the nature of a perfect cup of tea.",
    "What if memories could be traded like baseball cards?",
    "Design an app that allows you to experience historical events in first person.",
    "If silence had a texture, what would it feel like?",
    "Write a short story about a library where the books whisper secrets to readers.",
    "What if we discovered that plants are more intelligent than humans, just very slow?",
    "Describe a new sense that humans might evolve in the future.",
    "If emotions were Pokémon, what type would 'anxiety' be and what would be its signature move?",
    "Write an apology letter from humanity to the Earth's climate.",
    "What if trees communicated via a secret underground internet of roots (the 'wood wide web') about their day?",
    "Imagine a culinary dish that perfectly represents the concept of 'chaos'. What's in it?",
    "If all languages suddenly merged into one universal language overnight, what would be the pros and cons?",
    "Write a scientific paper on the hypothetical 'physics of friendship'.",
    "What if all graffiti was sentient and could comment on passersby?",
    "Design a system for rating dreams based on their cinematic quality.",
    "If ideas were visible as tiny, floating lights, what would a university campus look like at night?",
    "Write a travel blog post about visiting the center of the Earth.",
    "What if our solar system was just an atom in a much larger structure?",
    "Describe an AI's first experience of listening to music.",
    "If you could design an entirely new ecosystem, what bizarre creatures and plants would it contain?",
    "Write a job description for a professional cloud-watcher.",
    "What if humans could only speak in song lyrics for a day?",
    "Tell me a completely new fairytale.",
    "Imagine an algorithm that can predict your next thought. Would you want to know it?",
    "What's the most beautiful equation you've encountered, and why?",
    "Write a story from the perspective of the last star in the universe.",
    "If procrastination was a superpower, how could it be used for good?",
    "What if your reflection aged faster than you, showing glimpses of your future?",
    "Describe a world where your imagination literally shapes your reality.",
    "Write a national anthem for a country populated entirely by introverts.",
    "If you could make one abstract concept tangible for a day, which one and what would you do with it?",
    "What if gravity had an opinion about you?",
    "Compose a symphony that represents the entirety of human history.",
    "Imagine a world where emotions have colors that everyone can see. How would this change social interactions?",
    "Write a dialogue between a very old tree and a newly sprouted seedling.",
    "What if a popular conspiracy theory turned out to be true, but in a completely mundane and boring way?",
    "Describe a new fundamental force of nature and its effects.",
    "If books could feel pain, which book would be in the most agony from neglect?",
    "Write an owner's manual for a particularly moody black cat.",
    "What if your sneezes teleported you to random locations within a 1-mile radius?",
    "Invent a new word that describes the feeling of seeing a word you've just learned everywhere.",
    "If the internet had a physical form, what would it look like?",
    "Write a story about someone who discovers they are a background character in someone else's epic novel.",
    "What if memories could be edited like a movie scene?",
    "Describe a festival that celebrates the beauty of perfectly ordinary, everyday objects.",
    "If animals could vote in human elections, how would political campaigns change?",
    "Write a bedtime story for an adult who is afraid of the dark future.",
    "What if laughter was contagious like a yawn, but 100 times more potent?",
    "Design an experiment to determine if plants have a sense of humor.",
    "If different genres of music were species of animals, what would blues music be?",
    "Write a poem about the feeling of a forgotten password.",
    "What if the world was grayscale until you met your soulmate?",
    "Imagine a machine that translates the 'inner monologue' of babies.",
    "If you could add an extra hour to your day, but it had to be spent doing something completely useless, what would you do?",
    "Write a breakup letter to your own procrastination.",
    "What if we discovered a new primary color?",
    "Describe an alien trying to understand the concept of a 'weekend'.",
    "If clouds were made of solid objects that corresponded to their shapes, what would be the most interesting 'cloudfall'?",
    "Write a Yelp review for the universe.",
    "What if plants could only communicate through interpretive dance?",
    "Design a currency based on emotional experiences rather than material wealth.",
    "If historical figures had signature emojis, what would be Cleopatra's?",
    "Write a story about a city where the buildings rearrange themselves every night.",
    "What if the main character of every book you read looked exactly like you?",
    "Describe a planet where it rains tiny, harmless spiders twice a day.",
    "If jokes were a form of renewable energy, which comedian would power the world?",
    "Write a recipe for disaster (literally, what ingredients make things go wrong?).",
    "What if you could taste music? What would Beethoven's 5th taste like?",
    "Design a new type of public transportation inspired by an animal.",
    "If dreams were movies, who would be the highest-grossing director in your dreamscape?",
    "Write an instruction manual for dealing with a day where everything goes perfectly right.",
    "What if silence actually made a distinct sound, but most people have tuned it out?",
    "If different parts of your personality were roommates, who would be the messiest?",
    "Describe the experience of an AI trying to understand a human paradox.",
    "If you could only save three concepts from being forgotten by humanity, what would they be?",
    "Write a children's story about a shy volcano.",
    "What if the moon was actually made of cheese, but it was a really, really bland type of cheese?",
    "Generate a list of completely useless superpowers.",
    "If you could get a Ph.D. in any fictional subject, what would it be?",
    "Describe an object that could only exist in a dream.",
    "What if animals could create and appreciate art? What would a squirrel's masterpiece look like?",
    "Write a love story between an AI and a human from the AI's perspective.",
    "If the days of the week had personalities, what would Wednesday be like?",
    "Invent a holiday that has absolutely no historical or cultural significance, just for fun.",
    "What if you woke up one day and all text was in a language you didn't understand, but images were perfectly clear?",
    "Describe the taste of the color blue.",
    "If rocks were sentient but moved incredibly slowly, what epic tales would they tell over millennia?",
    "Write a script for a nature documentary about the common house dust bunny.",
    "What if we could exchange talents with other people for a day?",
    "Design an algorithm that generates truly original jokes, not just variations of existing ones.",
    "If your childhood imaginary friend became real for 24 hours, what would you do together?",
    "Write a set of commandments for modern internet etiquette.",
    "What if people could see a tiny meter above everyone's head indicating their current level of 'patience'?",
    "Describe a battle between the forces of 'Order' and 'Chaos', but they are just office workers.",
    "If every book had a soundtrack, what would be the main theme for 'Moby Dick'?",
    "Write a story where the main character communicates exclusively through puns.",
    "What if dreams could be recorded and watched later, but only in black and white with no sound?",
    "Create a new mythical creature that guards lost TV remotes.",
    "If different cloud types were different types of bread, what would a cirrus cloud be?",
    "Write a travel guide to a land where all the inhabitants are made of paper.",
    "What if a single, universally understood gesture for 'I'm sorry' existed for all species?",
    "Describe the philosophical implications of discovering that we are, in fact, living in a very advanced Tamagotchi."
  ],
    "email_queries": [
    "Help me write a professional email to my boss",
    "Draft an email to schedule a meeting with the team",
    "Compose a follow-up email for the client proposal",
    "Write an email declining a meeting invitation politely",
    "Help me respond to this customer complaint email",
    "Draft a thank you email after the interview",
    "Write an email requesting time off",
    "I need to send an email to HR about my benefits.",
    "Can you help me compose an email to a potential collaborator?",
    "Draft an email announcing a new project launch.",
    "Write an email to my team summarizing our weekly progress.",
    "Help me craft an email to a vendor about a late delivery.",
    "I need to write an apology email to a customer.",
    "Compose an email to congratulate a colleague on their promotion.",
    "Draft an email requesting feedback on a document.",
    "Write an email to introduce myself to a new team member.",
    "Help me formulate an email to ask for a letter of recommendation.",
    "I need to send an email to cancel an upcoming appointment.",
    "Compose an email to follow up on a job application.",
    "Draft an email to invite clients to a webinar.",
    "Write an email to my landlord about a maintenance issue.",
    "Help me write an email to a professor asking for an extension.",
    "I need to compose an out-of-office auto-reply email.",
    "Draft an email to a service provider to dispute a charge.",
    "Write an email to request a quote for services.",
    "Help me write an email to share meeting minutes.",
    "I need to send an email to confirm a reservation.",
    "Compose an email to express condolences.",
    "Draft an email to ask for clarification on a task.",
    "Write an email to resign from my position.",
    "Help me write a networking email to someone I met at a conference.",
    "I need to compose an email to update stakeholders on project status.",
    "Draft an email to a recruiter expressing interest in a role.",
    "Write an email to provide a reference for a former colleague.",
    "Help me draft an email to request a refund.",
    "I need to send an email reminder for an upcoming deadline.",
    "Compose an email to acknowledge receipt of an application.",
    "Draft an email to follow up on an unpaid invoice.",
    "Write an email to share a link to a new blog post with my subscribers.",
    "Help me write an email pitching a new idea to my manager.",
    "I need to compose an email to thank a speaker for their presentation.",
    "Draft an email to request an informational interview.",
    "Write an email to a client to inform them of a price change.",
    "Help me write an email to escalate an unresolved issue.",
    "I need to send an email to provide constructive criticism.",
    "Compose an email to accept a job offer.",
    "Draft an email to negotiate salary terms.",
    "Write an email to ask for volunteers for an event.",
    "Help me write an email to request a software license renewal.",
    "I need to compose an email to confirm attendance at an event.",
    "Draft an email to share a press release with media contacts.",
    "Write an email to follow up after a sales call.",
    "Help me write an email to decline a project offer.",
    "I need to send an email to request a testimonial from a happy client.",
    "Compose an email to announce an office relocation.",
    "Draft an email to a colleague to offer help on a project.",
    "Write an email to express appreciation for a gift.",
    "Help me write an email to inquire about partnership opportunities.",
    "I need to compose an email to set agenda for a meeting.",
    "Draft an email to welcome a new client.",
    "Write an email to inform team about a system maintenance schedule.",
    "Help me draft an email to request a change in a booking.",
    "I need to send an email to follow up on a lead.",
    "Compose an email to apologize for a missed deadline.",
    "Draft an email to invite someone to be a guest on a podcast.",
    "Write an email to a customer success manager about an account issue.",
    "Help me write an email to a potential investor.",
    "I need to compose an email to provide an update on a support ticket.",
    "Draft an email to ask for a LinkedIn connection with a personalized message.",
    "Write an email to confirm shipment of an order.",
    "Help me write an email to a government official.",
    "I need to send an email to request an internal transfer.",
    "Compose an email to announce a new company policy.",
    "Draft an email to a friend to catch up.",
    "Write an email to a family member planning a reunion.",
    "Help me write an email to a teacher about my child's progress.",
    "I need to compose an email to a contractor for a home renovation quote.",
    "Draft an email to decline an invitation to a social event.",
    "Write an email to ask for a sponsorship for a charity event.",
    "Help me write an email to a magazine editor submitting an article.",
    "I need to send an email to a booking agent for a performance.",
    "Compose an email to request a product demonstration.",
    "Draft an email to a client asking for missing information.",
    "Write an email to follow up on a previous email that got no response.",
    "Help me craft an email to a mentor asking for advice.",
    "I need to write an email to my team about a new workflow.",
    "Compose an email to congratulate someone on a new book release.",
    "Draft an email to ask for permission to use a copyrighted image.",
    "Write an email to a travel agency to plan a vacation.",
    "Help me write an email to a conference organizer about speaking opportunities.",
    "I need to compose an email to announce my retirement.",
    "Draft an email to a client to upsell a new service.",
    "Write an email to request a data export from a system admin.",
    "Help me write an email to a publisher with a book proposal.",
    "I need to send an email to a colleague to coordinate a presentation.",
    "Compose an email to follow up with attendees after a workshop.",
    "Draft an email to invite someone to join a professional organization.",
    "Write an email to a client who has overdue payments, gently reminding them.",
    "Help me write an email to set up a coffee chat with an industry peer.",
    "I need to compose an email to thank my team for their hard work on a project."
  ],
    "maps_queries": [
    "Convert '1600 Amphitheatre Parkway, Mountain View, CA' to coordinates.",
    "What are the latitude and longitude for the Eiffel Tower?",
    "Find the geographic coordinates of the White House.",
    "Geocode 'Buckingham Palace, London'.",
    "I need the coordinates for 'Times Square, New York'.",
    "What address is at latitude 34.0522 and longitude -118.2437?",
    "Tell me the address for coordinates 40.7128, -74.0060.",
    "Reverse geocode 48.8584° N, 2.2945° E.",
    "What's located at 51.5074° N, 0.1278° W?",
    "Give me the address for this point: lat 35.6895, lon 139.6917.",
    "Search for coffee shops near me.",
    "Find restaurants in downtown San Francisco.",
    "Show me parks within a 5km radius of my current location.",
    "Look for gas stations along Highway 101.",
    "Find ATMs near the 'Grand Central Terminal'.",
    "Search for 'best pizza places' in Chicago.",
    "What are some tourist attractions in Rome?",
    "Find me a Starbucks near latitude 40.7580, longitude -73.9855.",
    "Are there any museums around here?",
    "Search for 'hardware stores' in zip code 90210.",
    "Get details for place ID 'ChIJN1t_tDeuEmsRUsoyG83frY4'.",
    "Tell me more about the 'Louvre Museum'.",
    "What are the opening hours for 'The British Museum'?",
    "Find contact information for 'The Art Institute of Chicago'.",
    "Show me reviews for 'Central Park'.",
    "What's the rating for 'Golden Gate Bridge'?",
    "Get place details for the nearest grocery store.",
    "I need more info on 'ChIJgUbEo8cfqokR5lP9_Wh_xTQ'.",
    "What's the address and phone number for 'The Space Needle'?",
    "Are there photos available for 'Yosemite National Park'?",
    "Calculate the distance between 'New York, NY' and 'Los Angeles, CA'.",
    "How long would it take to drive from 'London' to 'Paris' and also from 'London' to 'Brussels'?",
    "What's the walking distance from 'my house' to 'the gym' and to 'the grocery store'?",
    "Get travel times for bicycling from 'Point A' to 'Point B' and 'Point C'.",
    "Provide a distance matrix for origins 'SFO Airport', 'Oakland Airport' and destinations 'Downtown SF', 'Palo Alto' using transit.",
    "How far is it from 'Berlin' to 'Munich' versus 'Berlin' to 'Hamburg' by car?",
    "Compare travel times from 'Home' to 'Work' and 'Home' to 'School'.",
    "What's the distance between 'Statue of Liberty' and 'Empire State Building'?",
    "How long to walk from 'Piccadilly Circus' to 'Trafalgar Square'?",
    "Distance and duration from 'Tokyo Station' to 'Shibuya Crossing' by transit.",
    "What's the elevation of Denver, Colorado?",
    "Get the altitude for a point at latitude 39.7392, longitude -104.9903.",
    "Find the elevation for these locations: Mount Everest base camp and Death Valley.",
    "Tell me the height above sea level for Lake Tahoe.",
    "What's the elevation data for coordinates 27.9881° N, 86.9250° E?",
    "Get elevation for my current location.",
    "What is the altitude of Machu Picchu?",
    "Elevation at Pikes Peak summit.",
    "Find the height of the terrain at these points: {lat: 46.8529, lon: -121.7604}, {lat: 36.5786, lon: -118.2920}.",
    "What's the elevation profile for a hike from ' trailhead A' to 'peak B'?",
    "Get directions from '1 Infinite Loop, Cupertino, CA' to 'San Francisco International Airport'.",
    "How do I get to the nearest hospital by car?",
    "Walking directions from my current location to 'Eiffel Tower'.",
    "Transit directions from 'Times Square' to 'Brooklyn Bridge'.",
    "Best cycling route from 'Golden Gate Park' to 'Sausalito'.",
    "Directions from 'Chicago O'Hare Airport' to 'The Bean'.",
    "How to get from 'Berlin Brandenburg Airport' to 'Brandenburg Gate' using public transport?",
    "Driving directions from 'Miami Beach' to 'Orlando'.",
    "Walking path from 'Westminster Abbey' to 'Buckingham Palace'.",
    "Show me the bike route from 'Amsterdam Centraal' to 'Rijksmuseum'.",
    "What's the quickest way to drive to 'Disneyland' from here?",
    "Find me a route to 'Yellowstone National Park' avoiding tolls.",
    "Directions to 'Grand Canyon South Rim' from 'Las Vegas'.",
    "How long will it take to walk to the closest coffee shop?",
    "Transit directions to 'Yankee Stadium' for a game tonight.",
    "Give me a route from 'LAX' to 'Santa Monica Pier'.",
    "Find the coordinates for 'Sydney Opera House'.",
    "What address corresponds to 43.6532° N, 79.3832° W?",
    "Search for 'pharmacies' near 'Union Station, Washington D.C.'.",
    "Get details for the 'CN Tower' in Toronto.",
    "What's the distance driving from 'Boston' to 'New York' and also 'Boston' to 'Philadelphia'?",
    "What is the elevation of Mount Fuji?",
    "Directions for driving from 'Vancouver, BC' to 'Calgary, AB'.",
    "Where is '123 Main St, Anytown, USA' on a map?",
    "Tell me what's at latitude 29.9792, longitude 31.1342.",
    "Find Italian restaurants within 2 miles of the 'Colosseum'.",
    "Show me the opening hours for 'The Metropolitan Museum of Art'.",
    "How far is it to walk from 'my hotel' to 'the beach' and to 'the main street'?",
    "What's the altitude of the Dead Sea shore?",
    "Get me transit directions from 'Heathrow Airport' to 'Central London'.",
    "Convert 'Taj Mahal, Agra, India' to lat/long.",
    "What is the address for 37.7749° N, 122.4194° W?",
    "Search for 'bookstores' in 'Greenwich Village, NYC'.",
    "Get me customer ratings for 'Space Needle'.",
    "Compare driving times from 'Home' to 'Client A Office' and 'Client B Office'.",
    "What is the elevation at the summit of Mount Kilimanjaro?",
    "Show me the driving route from 'Paris Charles de Gaulle Airport' to 'Louvre Museum'.",
    "Find the location of 'Berlin Wall Memorial'.",
    "What is near coordinates 34.0113° S, 18.4241° E (Cape Town)?",
    "Look for 'vegan restaurants' near 'Shibuya Crossing, Tokyo'.",
    "Are there any user reviews for 'Alcatraz Island'?",
    "How long does it take to cycle from 'Point X' to 'Point Y' versus 'Point X' to 'Point Z'?",
    "Tell me the height of Mount McKinley (Denali).",
    "Give me walking directions from 'Notre Dame Cathedral' to 'Shakespeare and Company bookstore'.",
    "Find coordinates for 'The Great Wall of China, Mutianyu section'.",
    "What's at latitude -33.8688, longitude 151.2093?",
    "Search for 'movie theaters' around 'Leicester Square, London'.",
    "Get me the phone number for 'The Getty Center'.",
    "What's the driving distance and time between 'Rome', 'Florence', and 'Venice' (all pairs)?",
    "Elevation of Kathmandu, Nepal.",
    "Directions from 'San Diego Zoo' to 'Balboa Park' by walking."
  ],
    "knowledge_base_queries": [
    "Did I ever ask about commit SH324GH in GitHub?",
    "What was the system's response when I asked about Jira ticket PROJ-789 last week?",
    "Find all my interactions related to the 'user authentication module'.",
    "Show me my conversation history regarding 'database migration planning'.",
    "Have I previously searched for weather in 'Paris'?",
    "What were my last three queries to the GitHub MCP?",
    "Can you remind me what I was working on last Tuesday related to 'API design'?",
    "Search my history for any questions about 'pull request review processes'.",
    "Did I ask for directions to '123 Main St' using the Maps MCP?",
    "What information did I request from the SQLite server yesterday?",
    "Were there any errors when I tried to create a Jira issue for 'UI bug'?",
    "Find discussions I had about 'performance bottlenecks' in the 'BackendService' repository.",
    "What was the first question I ever asked you about Confluence integration?",
    "Show me my interaction logs from Monday morning.",
    "Did I recently query the 'Customers' table in our SQLite database?",
    "Remind me of the file names I mentioned when discussing 'project report assets'.",
    "What did I ask about 'code scanning alerts' for the 'WebAppV2' GitHub repo?",
    "Have I made any Atlassian queries concerning 'sprint planning' this month?",
    "Find the time I asked about the 'stock price of GOOG'.",
    "What context did I provide when I searched for 'machine learning repositories' on GitHub?",
    "Show me a summary of my interactions regarding 'CI/CD pipeline setup'.",
    "Did I ever try to merge a pull request numbered #55 in the 'DataTools' repo?",
    "What was the outcome of my query about 'open issues assigned to me in Jira'?",
    "Have I looked up the 'get_issue_comments' tool for GitHub before?",
    "Search my activity for any mention of 'SQLite performance tuning'.",
    "What questions did I ask that involved the 'maps_distance_matrix' tool?",
    "Find my previous requests to the internet search MCP about 'latest AI research'.",
    "Did I ever ask you to create a new branch in GitHub named 'feature/KB-integration'?",
    "What did the system tell me when I asked for 'Jira project versions' for 'MobileAppX'?",
    "Remind me of the arguments I used when querying for 'commits by user 'dev_user'' on GitHub.",
    "Have I requested information about 'secret scanning alerts' for the 'InfraConfig' repository?",
    "What was my most recent query to the 'atlassian_queries' MCP?",
    "Find interactions where I asked about 'creating a Jira sprint'.",
    "Did I use the 'maps_geocode' tool for an address in Berlin?",
    "What did I look for in the 'Chinook' database around the start of the month?",
    "Have I asked for details on GitHub pull request #1022 from 'OrgY/RepoZ' before?",
    "What were the search terms when I looked for 'Python best practices' via internet search?",
    "Show me records of when I updated a Jira issue related to 'Task-451'.",
    "Did I interact with the 'list_notifications' tool on GitHub today?",
    "What collections of my activity are you currently tracking?",
    "Can you give me some info on the 'UserGitHubActivity' collection?",
    "How many of my interactions are stored in the 'JiraQueriesLog' collection?",
    "Let me peek at a few entries in the 'InternetSearches' collection.",
    "What's the total count of documents in my 'MapsUsage' collection?",
    "Has the 'SQLiteInteractionHistory' collection been modified recently?",
    "What was the purpose of the collection named 'GeneralSystemQueries'?",
    "Could you show me a sample document from my interaction history with the AI agent itself?",
    "What kind of metadata is stored with my 'GitHub_PR_discussions' entries?",
    "How many distinct types of interactions (collections) do you maintain for me?",
    "Did I ask about 'forking a repository' on GitHub in the last 7 days?",
    "Remind me about the Jira search I performed for 'issues labeled critical in project Alpha'.",
    "What was the address I used with the 'maps_reverse_geocode' tool on Friday?",
    "Have I queried the 'Products' table with a 'WHERE price > 100' clause recently?",
    "Search my knowledge base for any mention of 'embedding functions'.",
    "What was the system's reply when I asked to list Jira agile boards?",
    "Find my question about 'GitHub user search for 'data_expert''.",
    "Did I look for 'Confluence page children' for a page titled 'ProjectPlan_V2'?",
    "What was the context when I last used the 'read_query' tool for SQLite?",
    "Have I asked about 'traffic conditions' using the Maps MCP this week?",
    "Show me if I've ever inquired about 'GitHub Copilot review requests'.",
    "What did I want to know about the 'jira_get_worklog' tool?",
    "Find any history of me creating or updating a file in a GitHub repo named 'docs-site'.",
    "What questions have I asked regarding 'ChromaDB HNSW configuration'?",
    "Did I try to get details for a GitHub issue #77 in the 'frontend-framework' repo?",
    "What internet searches did I perform related to 'travel to Japan'?",
    "Remind me of any Jira issues I tried to transition to 'Closed'.",
    "Have I ever used the 'maps_elevation' tool for coordinates in the Alps?",
    "Show my queries to the SQLite MCP that involved 'JOIN operations'.",
    "What GitHub branches did I recently ask to compare?",
    "Find interactions where I asked to 'add a comment to a Jira issue'.",
    "Did I ask about 'points of interest' near a specific latitude/longitude using maps?",
    "What 'CREATE TABLE' statements have I executed via the SQLite MCP?",
    "Search my history for mentions of 'GitHub Actions workflow'.",
    "Have I logged any 'business insights' using the SQLite MCP this quarter?",
    "What parameters did I use with `chroma_query_documents` when looking for 'old Jira tickets'?",
    "Did I ever try to list tables from a database named 'AnalyticsDB'?",
    "Find the time I asked for 'GitHub commit history for the auth module'.",
    "Have I searched for information on 'Atlassian Crowd' using internet search?",
    "What was the Jira issue key when I asked about 'updating issue priority'?",
    "Did I request 'walking directions' to a place called 'Central Perk'?",
    "What was the content of the 'insight' I appended regarding 'Q3 sales figures'?",
    "Show me if I asked about the 'schema of the Employees table' in SQLite.",
    "What were the keywords in my query about 'GitHub repository search for 'AI tools''?",
    "Did I ever ask about 'deleting a Confluence page' titled 'Draft Notes'?",
    "What was the destination when I used the 'maps_directions' tool with mode 'transit'?",
    "Remind me about the SQL query I ran to find 'customers from London'.",
    "Have I used the term 'refactor' in any of my GitHub related queries?",
    "What JQL was involved when I searched for 'bugs fixed in the last sprint'?",
    "Did I ask for the 'place_id' of the 'CN Tower' from the maps service?",
    "What was the result when I tried to 'describe-table UserSessions' in SQLite?",
    "Find if I have any interaction records with metadata tag 'project:Omega'.",
    "Have I ever tried to update a document in ChromaDB related to a GitHub discussion?",
    "Show me all stored interactions where the MCP used was 'github_mcp'.",
    "What was the most recent document added to my 'UserJourneyLog' collection?",
    "Did I ask about 'deleting documents from a Chroma collection' before?",
    "Find my question related to 'GitLab' (even if it was routed to a general search or misrouted).",
    "Have I inquired about 'Jira issue link types' recently?",
    "What was the SQL query when I was looking for 'top 5 selling products'?",
    "Search my interaction history for the phrase 'API rate limits'.",
    "Did I ever mention a specific 'place_id' when talking to the Maps MCP?",
    "What were the details of my request to create a GitHub repository named 'MyTestProject'?",
    "Find all questions I asked that might relate to 'user privacy' or 'data security'."
  ],
    "sqlite_queries": [
    "Show me all records from the Customers table.",
    "List all products available.",
    "Get every order placed.",
    "Can you display all employees?",
    "Fetch data from the Suppliers table.",
    "Find customers who live in California.",
    "Show me orders that were placed in the last 30 days.",
    "Get products where the stock quantity is below 20 units.",
    "List employees hired after January 1st, 2023.",
    "Show me all invoices with an amount greater than $500.",
    "Display products sorted by their price, from highest to lowest.",
    "List customers alphabetically by last name.",
    "Show orders by their order date, most recent first.",
    "How many customers do we have in each city?",
    "What is the total sales amount for each product category?",
    "Calculate the average order value.",
    "Count the number of orders per customer.",
    "Show me the total number of products in stock.",
    "List all orders along with the customer's name who placed them.",
    "Get product names and their corresponding supplier names.",
    "Show employee details and the department they belong to.",
    "Find customers who haven't placed any orders in the past year.",
    "What are the top 10 best-selling products this month?",
    "Show me users who signed up last week.",
    "Get all unpaid invoices.",
    "List products that are currently out of stock.",
    "Find all sales transactions made yesterday.",
    "Show active subscriptions.",
    "Which employees are in the 'Sales' department?",
    "Get the details of the most recent order.",
    "What is the total revenue for Q1?",
    "Find the average salary in the engineering department.",
    "List all distinct countries where our customers are located.",
    "Show me comments posted on blog articles in the last 24 hours.",
    "Which products have a rating of 4 stars or higher?",
    "Get a list of all projects that are currently active.",
    "Find the names and email addresses of all subscribers.",
    "Show tasks that are due this week.",
    "What is the inventory level for 'Product X'?",
    "List all transactions for account 'ACC123'.",
    "Get me the name and price of all items in the 'Electronics' category.",
    "Show all customer support tickets that are still open.",
    "Find users who have logged in today.",
    "What's the total amount spent by customer ID 56?",
    "List all items in the 'Sales' table from the 'West' region.",
    "Add a new customer: Name 'Alice Wonderland', Email 'alice@example.com', City 'New York'.",
    "Insert a new product: Name 'Super Widget', Price 49.99, Stock 100.",
    "Record a new order for customer ID 101, product ID 202, quantity 2.",
    "Log a new employee: FirstName 'Bob', LastName 'Builder', Department 'Construction', Salary 60000.",
    "Add a new supplier: CompanyName 'Gadgets Inc.', ContactPerson 'Mr. Gizmo'.",
    "Update the email address for customer ID 303 to 'new.email@example.com'.",
    "Change the price of product ID 404 to 19.95.",
    "Increase the stock quantity for product 'Mega Gadget' by 25 units.",
    "Modify the status of order ID 505 to 'Shipped'.",
    "Update employee 'Eve Adams' salary to 75000.",
    "Change the department of employee ID 10 to 'Marketing'.",
    "Set the 'last_login' for user 'testuser' to the current timestamp.",
    "Mark invoice 'INV-007' as paid.",
    "Delete customer with ID 707.",
    "Remove order ID 808 from the database.",
    "Discontinue product 'Obsolete Item' by deleting it.",
    "Cancel subscription ID 'SUB-909'.",
    "Remove employee 'Tom Thumb' who has left the company.",
    "Delete all records from the 'TemporaryLogs' table.",
    "Archive orders older than 5 years by deleting them from the active 'Orders' table.",
    "Create a new table named 'Projects' with columns: ProjectID (integer, primary key), ProjectName (text), StartDate (date), Budget (real).",
    "Define a table called 'Tasks' having fields: TaskID, ProjectID, Description, DueDate, Status.",
    "Make a 'Departments' table with DepartmentID and DepartmentName.",
    "I need a table for 'ProductReviews' with ReviewID, ProductID, UserID, Rating, CommentText.",
    "Set up a 'UserActivityLog' table with LogID, UserID, ActivityType, Timestamp.",
    "What tables exist in this database?",
    "Show me a list of all tables.",
    "Can you list the names of all tables in the current database schema?",
    "Get all table names.",
    "Provide the table list for this SQLite database.",
    "Describe the structure of the 'Customers' table.",
    "What are the columns and data types in the 'Orders' table?",
    "Show me the schema for the 'Products' table.",
    "Can you detail the 'Employees' table definition?",
    "What fields are in the 'Invoices' table?",
    "Tell me about the 'Suppliers' table columns.",
    "I need the column information for the 'UserSessions' table.",
    "Provide the schema definition for 'Tasks'.",
    "What's the DDL for the 'Projects' table?",
    "Describe 'ProductCategories'.",
    "Show me the layout of the 'PaymentMethods' table.",
    "What columns does the 'Shipments' table have?",
    "Record this observation: Sales of 'Product X' have doubled in the last quarter.",
    "Add an insight: Customer engagement significantly increases after they use feature Y.",
    "Note for the team: There's a strong correlation between website traffic from social media and new sign-ups.",
    "Append this to business insights: The average resolution time for support tickets has decreased by 15%.",
    "Log this finding: Users in the 25-34 age group are the most active.",
    "Add to memo: Marketing campaign 'SummerSale' resulted in a 20% uplift in conversions.",
    "Record business insight: The new UI has led to a 10% reduction in cart abandonment.",
    "Insight: Inventory turnover for category 'Electronics' is higher than 'Apparel'.",
    "Add this to insights: 'Premium' tier subscribers have the highest lifetime value.",
    "Log the discovery: A/B test on the landing page showed version B performed 12% better.",
    "Memo: The churn rate is lowest among customers who have been with us for more than two years.",
    "Add the following to our business intelligence notes: West region showing slowest growth.",
    "Record insight: Most customer complaints are related to shipping delays."
  ],
    "unknown_queries": [
    "Help me with this thing.",
    "Can you do something about the issue?",
    "I need assistance with the problem.",
    "Fix this for me.",
    "Handle this request.",
    "Process this information.",
    "Deal with this situation.",
    "What about that?",
    "Can you check something?",
    "I have a question.",
    "Make it work.",
    "Tell me more.",
    "Explain that.",
    "What's next?",
    "And then?",
    "So, what now?",
    "How do I proceed?",
    "I'm stuck.",
    "This isn't right.",
    "Look into it.",
    "Figure it out.",
    "What are the options?",
    "Is there another way?",
    "Do your thing.",
    "Work your magic.",
    "Can you help?",
    "I need some support.",
    "Any ideas?",
    "What do you suggest?",
    "Let's try something.",
    "Okay, now what?",
    "About that report...",
    "Regarding the update...",
    "Concerning the previous topic...",
    "That thing we talked about.",
    "You know...",
    "The usual.",
    "Same as before.",
    "Can you find it?",
    "Where is it?",
    "What was that again?",
    "I forgot.",
    "Remind me.",
    "Can you show me?",
    "Just do it.",
    "Get it done.",
    "Is it ready?",
    "What's the status?",
    "Update me.",
    "Any news?",
    "What happened?",
    "Tell me about it.",
    "I need information.",
    "Give me the details.",
    "Expand on that.",
    "Elaborate please.",
    "Can you clarify?",
    "I don't understand.",
    "This is confusing.",
    "What does this mean?",
    "Sort this out.",
    "Organize this.",
    "Find a solution.",
    "I have a problem here.",
    "It's not working as expected.",
    "There's an error.",
    "Something went wrong.",
    "Can you look at this file?",
    "What about this data?",
    "This needs attention.",
    "Address this.",
    "What are your thoughts?",
    "I'm not sure about this.",
    "Can you advise?",
    "Help me decide.",
    "What should I do?",
    "Let's move forward.",
    "Next step?",
    "What's the plan?",
    "I need a strategy.",
    "How to approach this?",
    "Give me some guidance.",
    "Any suggestions for this task?",
    "The item.",
    "That specific case.",
    "The project.",
    "You know, the thing with the server.",
    "About yesterday's query.",
    "Follow up on that.",
    "Let's revisit that.",
    "What's the latest on it?",
    "Is there any progress?",
    "I need to know more about the process.",
    "Can you help me with settings?",
    "This configuration.",
    "The setup.",
    "Just explore.",
    "Analyze this for me.",
    "Provide an overview."
  ]
}
